# Generated by Django 4.1.2 on 2022-10-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanhiaAerea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'companhia_aerea',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('horario_previsto', models.TimeField()),
                ('local', models.CharField(max_length=200)),
                ('companhia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_voos.companhiaaerea')),
            ],
            options={
                'db_table': 'voo',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('horario_real', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('EM', 'Embarcando'), ('CA', 'Cancelado'), ('PR', 'Embarcando'), ('TA', 'Taxeando'), ('PO', 'Pronto'), ('AU', 'Autorizado'), ('VO', 'Em voo')], default='EM', max_length=2)),
                ('data', models.DateTimeField()),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_voos.voo')),
            ],
            options={
                'db_table': 'partida',
            },
        ),
        migrations.CreateModel(
            name='Chegada',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('horario_real', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('VO', 'Em voo'), ('AT', 'Aterrisado')], default='VO', max_length=2)),
                ('data', models.DateTimeField()),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_voos.voo')),
            ],
            options={
                'db_table': 'chegada',
            },
        ),
    ]
