# Generated by Django 4.1.2 on 2022-11-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_voos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='codigo',
            field=models.CharField(default='AA0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='companhiaaerea',
            name='codigo',
            field=models.CharField(max_length=2),
        ),
    ]
