# Generated by Django 4.1.2 on 2022-11-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_voos', '0002_voo_codigo_alter_companhiaaerea_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='companhia',
            field=models.CharField(max_length=50),
        ),
    ]
