# Generated by Django 4.1.2 on 2022-11-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_voos', '0003_alter_voo_companhia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='companhia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_voos.companhiaaerea'),
        ),
    ]
