# Generated by Django 4.1.2 on 2022-11-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_voos', '0004_alter_voo_companhia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='status',
            field=models.CharField(choices=[('EM', 'Embarcando'), ('CA', 'Cancelado'), ('PR', 'Programado'), ('TA', 'Taxeando'), ('PO', 'Pronto'), ('AU', 'Autorizado'), ('VO', 'Em voo')], default='EM', max_length=2),
        ),
    ]
