# Generated by Django 4.1.2 on 2022-11-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_voos', '0005_alter_partida_data_alter_partida_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chegada',
            name='horario_real',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='horario_real',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
