# Generated by Django 4.1.2 on 2022-11-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_voos', '0006_alter_chegada_horario_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chegada',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
